apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
spec:
  selector:
    matchLabels:
      app: todo-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - image: mysql
        name: todo-db
        env:
          - name: MYSQL_DATABASE
            value: "db_tasks"
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    use db_tasks;
    create table tasks (
        id INT(10) NOT NULL AUTO_INCREMENT,
        title VARCHAR(10) NOT NULL,
        PRIMARY KEY (id)
    );
