apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  selector:
    matchLabels:
      app: todo-frontend
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - image: vivekk2104/todo-frontend:latest
          imagePullPolicy: Always
          name: todo-frontend
          ports:
            - containerPort: 3000
